### ISSUE TITLE
Offset date from web/front/date.ts formatDate()

### ISSUE THREAD

**Issue by 1998marcom** [cirosantilli/ourbigbook#233]
In the ArticleList page (e.g. [ourbigbook.com/go/latest](https://ourbigbook.com/go/latest)) "created" and "updated" dates have the wrong month number. The month number is printed by the `formatDate` function, defined in `web/front/date.ts`, using `date.getMonth()`.
As per the docs, date.getMonth() returns something between 0 and 11, not between 1 and 12.

**Comment by cirosantilli** [comment]
Thanks!
